- name: Enable 'AppRole' Authentication
  uri:
    url: "{{ url_vault_api_auth }}/approle"
    method: POST
    headers: 
      X-Vault-Token: "{{ vault_token }}"
    body_format: json
    body:
      type: approle
    status_code: 204,400
  register: reg_response
  failed_when: "reg_response.status == 400 and 'path is already in use' not in reg_response.json.errors"

- debug:
    msg: "{{ reg_response }}"