- name: Create namespace '{{ namespace }}'
  uri:
    url: "{{ url_vault_api_namespaces }}/{{ namespace }}"
    method: POST
    headers: 
      X-Vault-Token: "{{ vault_token }}"
    body_format: json
    status_code: 200,204,400
  register: reg_response
  failed_when: "reg_response.status == 400 and 'path is already in use' not in reg_response.json.errors"

- debug:
    msg: "{{ reg_response }}"