#
# ansible-playbook -e plugin_name=plugin_test -e plugin_type=callback create_ansible_plugin.yml
# 
- hosts: localhost
  gather_facts: no

  vars:
    project: "{{ castle_gitlab_ansible_plugin_prefix }}-{{ plugin_type }}-{{ plugin_name }}"

  roles:
    - castle_gitlab

  tasks:
    - include_tasks: roles/castle_gitlab/tasks/project_create.yml
      vars:
        project_name: "{{ project }}"

    - include_tasks: roles/castle_gitlab/tasks/project_add_issue_label.yml
      vars:
        project_name: "{{ project }}"
        issue_label: "{{ item }}"
      with_items:
        - "{{ castle_gitlab_ansible_issue_labels }}"